<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- Versión de la plantilla POM (en Maven 2 y 3 siempre es 4.0.0) -->
    <modelVersion>4.0.0</modelVersion>

    <!-- Coordenadas de tu proyecto -->
    <groupId>com.miguelherrog</groupId>
    <artifactId>memory-checkpoint</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- Configuración del compilador -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.2.0</version>
        </dependency>
    </dependencies>

</project>